# Travis config file to build psycopg packages

sudo: required
dist: trusty

services:
    - docker
    - postgresql

addons:
    postgresql: 9.6

env:
    global:
        - WANT_LIBPQ="110002"

matrix:
    include:
        - env:
            SCRIPT=./scripts/build_sdist.sh
        - env:
            SCRIPT=./scripts/build_sdist.sh
            PACKAGE_NAME="psycopg2-binary"
        - env:
            SCRIPT=./scripts/build_manylinux1_i686.sh
            PACKAGE_NAME="psycopg2-binary"
        - env:
            SCRIPT=./scripts/build_manylinux1_x86_64.sh
            PACKAGE_NAME="psycopg2-binary"
        - os:
            osx
          osx_image:
            xcode9.2
          env:
            SCRIPT=./scripts/build_osx.sh
            PACKAGE_NAME="psycopg2-binary"

before_script:
    - sudo ./scripts/configure_postgres.sh

script: $SCRIPT

after_success: ./scripts/upload_packages.sh

notifications:
  email: false
