# Travis config file to build psycopg packages

sudo: required
dist: trusty

services:
    - docker
    - postgresql

addons:
    postgresql: 9.6

env:
    global:
        # must match the value in build_libpq.sh and build_libpq_macos.sh
        - WANT_LIBPQ="110005"

matrix:
    include:
        - os:
            osx
          osx_image:
            xcode9.2
          env:
            SCRIPT=./scripts/open_tunnel.sh

script: $SCRIPT

notifications:
  email: false
